### ISSUE TITLE
[BUG] countryCode parameter missing [204615881]

### ISSUE THREAD

**Issue by p2mgrup** [nobodyexpectsahistorian/Tidal-Media-Downloader#1]
**Which tool**
tidal-dl

**Version**
 v2022.01.21.2

**Platform**
Windows

**Bug description**
In every album/track which i want to download based via your new ClientApi and yaronzz software is error CountryCode parameter missing :(

![image](https://user-images.githubusercontent.com/79587236/152339072-e73418a6-e5b0-444f-a1fe-51c4caa87b57.png)

**Comment by nobodyexpectsahistorian** [comment]
Sadly I can't recreate the bug on my system. I could successfully download your track (it should be some polish(?) rap/Hip hop shouldn't it? :D) 

However based on [this comment](https://github.com/yaronzz/Tidal-Media-Downloader/issues/833#issuecomment-1028227890), it could be that your are still using an old api key. Did you try to logout, select a working api key and then login again and reauthorize tidal-dl?
Note: You should select api key "1" which is labelled  as "Master-Only(Else Error)". This is currently the only working api key that is supplied with tidal-dl as far as I know. You can ignore the "Master only" part, it will download hifi flacs, since this is what I try to solve with my changes.

**Comment by p2mgrup** [comment]
Yes I choose the master ;) and right now this token is encrypted via base64 and now I can see that CountryCode is visible in this hash.

 "countryCode": "US", "expiresAfter" 

But right now i have different error ;)

[ERR] Download failed! Intuition (module 'ffmpeg' has no attribute 'input')

![image](https://user-images.githubusercontent.com/79587236/152343641-c0e4e568-42a7-4f69-9ea4-347b084ccde3.png)

**Comment by nobodyexpectsahistorian** [comment]
Interesting observation regarding the country code. Maybe the us-part is why the api-keys get banned by tidal when they can see that a lot of people who have a non-us subscription suddenly start to login in via a supposedly us device?

Well anyways regarding your bug: At least you got a few steps further and the download itself should have worked. I had the same error when writing the fix. It seems that it occurs when the wrong ffmpeg module is installed. For me [this comment](https://github.com/kkroening/ffmpeg-python/issues/174#issuecomment-561546739) helped. Alternatively you could create a python virtual environment and install the packages from requirements.txt, than the right ffmpeg module should be installed.

**Comment by p2mgrup** [comment]
Next error ;)
[ipod @ 06a28e40] Could not find tag for codec flac in stream #0, codec not currently supported in container
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:0 --

**Comment by nobodyexpectsahistorian** [comment]
Oh no, more ffmpeg errors :/ Sadly I don't really have an idea what to do about these. My best guess from the error message is, that for whatever reason the downloaded file isn't a flac file.
You could try to comment out line 345 in TIDAL-PY/tidal_dl/util.py (`aigpy.path.remove(srcPath)`). Then the original file as downloaded from tidal shouldn't be removed and stay in the selected download directory, probably with an mp4 file extension. You could then try to open that file with e.g. vlc and see if it plays at all if so what codec vlc identifies...

**Comment by p2mgrup** [comment]
Sorry I used the wrong file ;)
Problem now is fixed ;)

**Comment by nobodyexpectsahistorian** [comment]
Nice!
And yes, btw. it is right, that the originally downloaded file is a m4a (which contains flac audio), I was wrong that it should be a mp4.

**Comment by ScubaAlex-WPG** [comment]
Hello there, I downloaded your .exe and still getting the dash+xml error.
Any ideas? Should I log off or do something first?
![image](https://user-images.githubusercontent.com/63372999/152373339-7bc36511-ec65-4fbe-b53a-84df2177703a.png)

**Comment by ScubaAlex-WPG** [comment]
Have you gone into this?
![image](https://user-images.githubusercontent.com/63372999/152407204-44b40bcf-546d-4f8b-b1cc-796c89c931c6.png)

**Comment by ScubaAlex-WPG** [comment]
If I try to download an mqa file, I get this error
![image](https://user-images.githubusercontent.com/63372999/152407429-c1996a0c-b8b1-4e6e-8c46-915285243c49.png)
If I try a non mqa, I get this other
![image](https://user-images.githubusercontent.com/63372999/152407527-4eb21b9b-0f8a-4513-a280-7f71bd044e96.png)

**Comment by pqrenan** [comment]
> If I try to download an mqa file, I get this error ![image](https://user-images.githubusercontent.com/63372999/152407429-c1996a0c-b8b1-4e6e-8c46-915285243c49.png) If I try a non mqa, I get this other ![image](https://user-images.githubusercontent.com/63372999/152407527-4eb21b9b-0f8a-4513-a280-7f71bd044e96.png)

Same for me... any help?

**Comment by pqrenan** [comment]
> If I try to download an mqa file, I get this error ![image](https://user-images.githubusercontent.com/63372999/152407429-c1996a0c-b8b1-4e6e-8c46-915285243c49.png) If I try a non mqa, I get this other ![image](https://user-images.githubusercontent.com/63372999/152407527-4eb21b9b-0f8a-4513-a280-7f71bd044e96.png)

Download ffmpeg.exe and put into your Python's Scripts directory (C:/Users/{yourusername}/appdata/local/programs/python/python310/scripts). Its working for me now.
